server {
    listen 8108;
    root /var/www/TiFdizzymall;
    index index.html;
    server_name _;
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    location / { try_files $uri $uri/ =404; }
}
